=== vonlinee/mybatis-3/src/main/resources/org/apache/ibatis/builder/xml/mybatis-3-mapper.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!--

       Copyright 2009-2026 the original author or authors.

       Licensed under the Apache License, Version 2.0 (the "License");
       you may not use this file except in compliance with the License.
       You may obtain a copy of the License at

          https://www.apache.org/licenses/LICENSE-2.0

       Unless required by applicable law or agreed to in writing, software
       distributed under the License is distributed on an "AS IS" BASIS,
       WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
       See the License for the specific language governing permissions and
       limitations under the License.

-->
<!ELEMENT mapper (cache-ref | cache | resultMap* | parameterMap* | sql* | insert* | update* | delete* | select* )+>
<!ATTLIST mapper
namespace CDATA #IMPLIED
>

<!ELEMENT cache-ref EMPTY>
<!ATTLIST cache-ref
namespace CDATA #REQUIRED
>

<!ELEMENT cache (property*)>
<!ATTLIST cache
type CDATA #IMPLIED
eviction CDATA #IMPLIED
flushInterval CDATA #IMPLIED
size CDATA #IMPLIED
readOnly CDATA #IMPLIED
blocking CDATA #IMPLIED
>

<!ELEMENT parameterMap (parameter+)?>
<!ATTLIST parameterMap
id CDATA #REQUIRED
type CDATA #REQUIRED
>

<!ELEMENT parameter EMPTY>
<!ATTLIST parameter
property CDATA #REQUIRED
javaType CDATA #IMPLIED
jdbcType CDATA #IMPLIED
mode (IN | OUT | INOUT) #IMPLIED
resultMap CDATA #IMPLIED
scale CDATA #IMPLIED
typeHandler CDATA #IMPLIED
>

<!ELEMENT resultMap (constructor?,id*,result*,association*,collection*, discriminator?)>
<!ATTLIST resultMap
id CDATA #REQUIRED
type CDATA #REQUIRED
extends CDATA #IMPLIED
autoMapping (true|false) #IMPLIED
>

<!ELEMENT constructor ((idArg|arg)*)>

<!ELEMENT id EMPTY>
<!ATTLIST id
property CDATA #IMPLIED
javaType CDATA #IMPLIED
column CDATA #IMPLIED
jdbcType CDATA #IMPLIED
typeHandler CDATA #IMPLIED
>

<!ELEMENT result EMPTY>
<!ATTLIST result
property CDATA #IMPLIED
javaType CDATA #IMPLIED
column CDATA #IMPLIED
jdbcType CDATA #IMPLIED
typeHandler CDATA #IMPLIED
>

<!ELEMENT idArg EMPTY>
<!ATTLIST idArg
javaType CDATA #IMPLIED
column CDATA #IMPLIED
jdbcType CDATA #IMPLIED
typeHandler CDATA #IMPLIED
select CDATA #IMPLIED
resultMap CDATA #IMPLIED
name CDATA #IMPLIED
columnPrefix CDATA #IMPLIED
>

<!ELEMENT arg EMPTY>
<!ATTLIST arg
javaType CDATA #IMPLIED
column CDATA #IMPLIED
jdbcType CDATA #IMPLIED
typeHandler CDATA #IMPLIED
select CDATA #IMPLIED
resultMap CDATA #IMPLIED
name CDATA #IMPLIED
columnPrefix CDATA #IMPLIED
>

<!ELEMENT collection (constructor?,id*,result*,association*,collection*, discriminator?)>
<!ATTLIST collection
property CDATA #REQUIRED
column CDATA #IMPLIED
javaType CDATA #IMPLIED
ofType CDATA #IMPLIED
jdbcType CDATA #IMPLIED
select CDATA #IMPLIED
resultMap CDATA #IMPLIED
typeHandler CDATA #IMPLIED
notNullColumn CDATA #IMPLIED
columnPrefix CDATA #IMPLIED
resultSet CDATA #IMPLIED
foreignColumn CDATA #IMPLIED
autoMapping (true|false) #IMPLIED
fetchType (lazy|eager) #IMPLIED
>

<!ELEMENT association (constructor?,id*,result*,association*,collection*, discriminator?)>
<!ATTLIST association
property CDATA #REQUIRED
column CDATA #IMPLIED
javaType CDATA #IMPLIED
jdbcType CDATA #IMPLIED
select CDATA #IMPLIED
resultMap CDATA #IMPLIED
typeHandler CDATA #IMPLIED
notNullColumn CDATA #IMPLIED
columnPrefix CDATA #IMPLIED
resultSet CDATA #IMPLIED
foreignColumn CDATA #IMPLIED
autoMapping (true|false) #IMPLIED
fetchType (lazy|eager) #IMPLIED
>

<!ELEMENT discriminator (case+)>
<!ATTLIST discriminator
column CDATA #IMPLIED
javaType CDATA #REQUIRED
jdbcType CDATA #IMPLIED
typeHandler CDATA #IMPLIED
>

<!ELEMENT case (constructor?,id*,result*,association*,collection*, discriminator?)>
<!ATTLIST case
value CDATA #REQUIRED
resultMap CDATA #IMPLIED
resultType CDATA #IMPLIED
>

<!ELEMENT property EMPTY>
<!ATTLIST property
name CDATA #REQUIRED
value CDATA #REQUIRED
>

<!ELEMENT typeAlias EMPTY>
<!ATTLIST typeAlias
alias CDATA #REQUIRED
type CDATA #REQUIRED
>

<!ELEMENT select (#PCDATA | include | trim | where | set | foreach | choose | if | bind | in | pagination | columns)*>
<!ATTLIST select
id CDATA #REQUIRED
parameterMap CDATA #IMPLIED
parameterType CDATA #IMPLIED
resultMap CDATA #IMPLIED
resultType CDATA #IMPLIED
resultSetType (FORWARD_ONLY | SCROLL_INSENSITIVE | SCROLL_SENSITIVE | DEFAULT) #IMPLIED
statementType (STATEMENT|PREPARED|CALLABLE) #IMPLIED
fetchSize CDATA #IMPLIED
timeout CDATA #IMPLIED
flushCache (true|false) #IMPLIED
useCache (true|false) #IMPLIED
databaseId CDATA #IMPLIED
lang CDATA #IMPLIED
resultOrdered (true|false) #IMPLIED
resultSets CDATA #IMPLIED 
affectData (true|false) #IMPLIED
countStatement CDATA #IMPLIED
namingStrategy (LOWER_UNDERSCORE_TO_LOWER_CAMEL|UPPER_UNDERSCORE_TO_LOWER_CAMEL|LOWER_CAMEL_TO_LOWER_CAMEL) #IMPLIED
>

<!ELEMENT insert (#PCDATA | selectKey | include | trim | where | set | foreach | choose | if | bind | in | pagination)*>
<!ATTLIST insert
id CDATA #REQUIRED
parameterMap CDATA #IMPLIED
parameterType CDATA #IMPLIED
timeout CDATA #IMPLIED
flushCache (true|false) #IMPLIED
statementType (STATEMENT|PREPARED|CALLABLE) #IMPLIED
keyProperty CDATA #IMPLIED
useGeneratedKeys (true|false) #IMPLIED
keyColumn CDATA #IMPLIED
databaseId CDATA #IMPLIED
lang CDATA #IMPLIED
>

<!ELEMENT selectKey (#PCDATA | include | trim | where | set | foreach | choose | if | bind | in | pagination)*>
<!ATTLIST selectKey
resultType CDATA #IMPLIED
statementType (STATEMENT|PREPARED|CALLABLE) #IMPLIED
keyProperty CDATA #IMPLIED
keyColumn CDATA #IMPLIED
order (BEFORE|AFTER) #IMPLIED
databaseId CDATA #IMPLIED
>

<!ELEMENT update (#PCDATA | selectKey | include | trim | where | set | foreach | choose | if | bind | in | pagination)*>
<!ATTLIST update
id CDATA #REQUIRED
parameterMap CDATA #IMPLIED
parameterType CDATA #IMPLIED
timeout CDATA #IMPLIED
flushCache (true|false) #IMPLIED
statementType (STATEMENT|PREPARED|CALLABLE) #IMPLIED
keyProperty CDATA #IMPLIED
useGeneratedKeys (true|false) #IMPLIED
keyColumn CDATA #IMPLIED
databaseId CDATA #IMPLIED
lang CDATA #IMPLIED
>

<!ELEMENT delete (#PCDATA | include | trim | where | set | foreach | choose | if | bind | in | pagination)*>
<!ATTLIST delete
id CDATA #REQUIRED
parameterMap CDATA #IMPLIED
parameterType CDATA #IMPLIED
timeout CDATA #IMPLIED
flushCache (true|false) #IMPLIED
statementType (STATEMENT|PREPARED|CALLABLE) #IMPLIED
databaseId CDATA #IMPLIED
lang CDATA #IMPLIED
>

<!-- Dynamic -->

<!ELEMENT include (property+)?>
<!ATTLIST include
refid CDATA #REQUIRED
>

<!ELEMENT bind EMPTY>
<!ATTLIST bind
 name CDATA #REQUIRED
 value CDATA #REQUIRED
>

<!ELEMENT columns (#PCDATA)>
<!ATTLIST columns
table CDATA #IMPLIED
>

<!ELEMENT sql (#PCDATA | include | trim | where | set | foreach | choose | if | bind | in | pagination)*>
<!ATTLIST sql
id CDATA #REQUIRED
lang CDATA #IMPLIED
databaseId CDATA #IMPLIED
scope (private|public) #IMPLIED
>

<!ELEMENT trim (#PCDATA | include | trim | where | set | foreach | choose | if | bind | in | pagination)*>
<!ATTLIST trim
prefix CDATA #IMPLIED
prefixOverrides CDATA #IMPLIED
suffix CDATA #IMPLIED
suffixOverrides CDATA #IMPLIED
>
<!ELEMENT where (#PCDATA | include | trim | where | set | foreach | choose | if | bind | in | pagination)*>
<!ELEMENT set (#PCDATA | include | trim | where | set | foreach | choose | if | bind | in | pagination)*>

<!ELEMENT foreach (#PCDATA | include | trim | where | set | foreach | choose | if | bind | in | pagination)*>
<!ATTLIST foreach
collection CDATA #REQUIRED
nullable (true|false) #IMPLIED
item CDATA #IMPLIED
index CDATA #IMPLIED
open CDATA #IMPLIED
close CDATA #IMPLIED
separator CDATA #IMPLIED
>

<!ELEMENT in (#PCDATA | include | trim | where | set | foreach | choose | if | bind | in | pagination)*>
<!ATTLIST in
collection CDATA #REQUIRED
nullable (true|false) #IMPLIED
column CDATA #IMPLIED
item CDATA #IMPLIED
index CDATA #IMPLIED
>

<!ELEMENT pagination EMPTY>
<!ATTLIST pagination
>

<!ELEMENT choose (when* , otherwise?)>
<!ELEMENT when (#PCDATA | include | trim | where | set | foreach | choose | if | bind | in | pagination)*>
<!ATTLIST when
test CDATA #REQUIRED
>
<!ELEMENT otherwise (#PCDATA | include | trim | where | set | foreach | choose | if | bind | in | pagination)*>

<!ELEMENT if (#PCDATA | include | trim | where | set | foreach | choose | if | bind | in | pagination)*>
<!ATTLIST if
test CDATA #REQUIRED
>

=== vonlinee/mybatis-3/src/test/java/org/apache/ibatis/submitted/methodoverloading/Mapper.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

       Copyright 2009-2026 the original author or authors.

       Licensed under the Apache License, Version 2.0 (the "License");
       you may not use this file except in compliance with the License.
       You may obtain a copy of the License at

          https://www.apache.org/licenses/LICENSE-2.0

       Unless required by applicable law or agreed to in writing, software
       distributed under the License is distributed on an "AS IS" BASIS,
       WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
       See the License for the specific language governing permissions and
       limitations under the License.

-->
<!DOCTYPE mapper
        PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN"
        "http://mybatis.org/dtd/mybatis-3-mapper.dtd">

<mapper namespace="org.apache.ibatis.submitted.methodoverloading.Mapper">

    <resultMap id="userWithFriend" type="org.apache.ibatis.submitted.methodoverloading.User">
        <id property="id" column="id"/>
        <result property="name" column="name"/>
        <association property="friend" select="selectByIdAndName" column="{id=id,name=name}"/>
    </resultMap>

    <select id="selectById" resultType="org.apache.ibatis.submitted.methodoverloading.User">
        select * from users where id = #{id}
    </select>

    <insert id="insert#User">
        insert into users values (#{id}, #{name})
    </insert>

    <insert id="insert#int[]_String">
        insert into users values
        <foreach item="i" collection="uids" separator=",">
            (#{i}, concat(#{namePrefix}, #{i}))
        </foreach>
    </insert>

</mapper>

=== vonlinee/mybatis-3/src/test/java/org/apache/ibatis/submitted/ognl_static_simplify/Mapper.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

       Copyright 2009-2026 the original author or authors.

       Licensed under the Apache License, Version 2.0 (the "License");
       you may not use this file except in compliance with the License.
       You may obtain a copy of the License at

          https://www.apache.org/licenses/LICENSE-2.0

       Unless required by applicable law or agreed to in writing, software
       distributed under the License is distributed on an "AS IS" BASIS,
       WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
       See the License for the specific language governing permissions and
       limitations under the License.

-->
<!DOCTYPE mapper
        PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN"
        "https://mybatis.org/dtd/mybatis-3-mapper.dtd">

<mapper namespace="org.apache.ibatis.submitted.ognl_static_simplify.SimplifyStaticFunctionTest$Mapper">

    <select id="selectUsers"
            resultType="org.apache.ibatis.submitted.ognl_static_simplify.SimplifyStaticFunctionTest$User">
        select * from users
        <where>
            <if test="@isNotEmpty(param.name)">
                name = #{param.name}
            </if>
        </where>
    </select>

    <select id="selectUsers1"
            resultType="org.apache.ibatis.submitted.ognl_static_simplify.SimplifyStaticFunctionTest$User">
        select * from users
        <where>
            <choose>
                <when test="@isNotEmpty(param.id)">
                    id = #{param.id}
                </when>
            </choose>
        </where>
    </select>
</mapper>

=== vonlinee/mybatis-3/src/test/java/org/apache/ibatis/submitted/methodoverloading/XmlMapperWithConflictStatementId.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

       Copyright 2009-2026 the original author or authors.

       Licensed under the Apache License, Version 2.0 (the "License");
       you may not use this file except in compliance with the License.
       You may obtain a copy of the License at

          https://www.apache.org/licenses/LICENSE-2.0

       Unless required by applicable law or agreed to in writing, software
       distributed under the License is distributed on an "AS IS" BASIS,
       WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
       See the License for the specific language governing permissions and
       limitations under the License.

-->
<!DOCTYPE mapper PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN" "https://mybatis.org/dtd/mybatis-3-mapper.dtd">
<mapper namespace="org.apache.ibatis.submitted.methodoverloading.UserMapper">
    <select id="findUser" resultType="String">
        SELECT name FROM users
        <where>
            <if test="id != null">
                id = #{id}
            </if>
            <if test="email != null">
                AND email = #{email}
            </if>
        </where>
    </select>

    <select id="findUser" resultType="String">
        SELECT name FROM users
        <where>
            <if test="id != null">
                id = #{id}
            </if>
        </where>
    </select>
</mapper>

=== vonlinee/mybatis-3/src/test/resources/org/apache/ibatis/submitted/includes/Mapper.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

       Copyright 2009-2024 the original author or authors.

       Licensed under the Apache License, Version 2.0 (the "License");
       you may not use this file except in compliance with the License.
       You may obtain a copy of the License at

          https://www.apache.org/licenses/LICENSE-2.0

       Unless required by applicable law or agreed to in writing, software
       distributed under the License is distributed on an "AS IS" BASIS,
       WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
       See the License for the specific language governing permissions and
       limitations under the License.

-->
<!DOCTYPE mapper
    PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN"
    "https://mybatis.org/dtd/mybatis-3-mapper.dtd">

<mapper namespace="org.apache.ibatis.submitted.includes.mapper">
  <sql id="sometable">
    ${prefix}Table
  </sql>
  <sql id="tableName">
    SomeTable
  </sql>

  <sql id="someinclude">
    <include ref="${include_target}"/>
  </sql>

  <select id="select" resultType="map">
    <include ref="someinclude">
        <property name="include_target" value="org.apache.ibatis.submitted.includes.fragments.select"/>
    </include>
    field1, field2, field3
    from
      <include ref="someinclude">
          <property name="prefix" value="Some"/>
          <property name="include_target" value="sometable"/>
      </include>
  </select>

  <select id="selectWithProperty" resultType="_int">
    <include ref="${ns}.values"/>
  </select>

  <update id="update" parameterType="map">
    <include ref="org.apache.ibatis.submitted.includes.fragments.update"/>
    <include ref="org.apache.ibatis.submitted.includes.mapper.sometable">
        <property name="prefix" value="Some"/>
    </include>
    set Field2 = #{field2,jdbcType=INTEGER},
    Field3 = #{field3,jdbcType=VARCHAR},
    where field1 = #{field1,jdbcType=INTEGER}
  </update>

  <select id="selectIds" resultType="int">
    <include ref="org.apache.ibatis.submitted.includes.fragments.selectId"/>
  </select>
</mapper>

=== vonlinee/mybatis-3/src/test/java/org/apache/ibatis/submitted/sql_render/Mapper.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!--

       Copyright 2009-2026 the original author or authors.

       Licensed under the Apache License, Version 2.0 (the "License");
       you may not use this file except in compliance with the License.
       You may obtain a copy of the License at

          https://www.apache.org/licenses/LICENSE-2.0

       Unless required by applicable law or agreed to in writing, software
       distributed under the License is distributed on an "AS IS" BASIS,
       WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
       See the License for the specific language governing permissions and
       limitations under the License.

-->
<!DOCTYPE mapper
        PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN"
        "https://mybatis.org/dtd/mybatis-3-mapper.dtd">

<mapper namespace="org.apache.ibatis.submitted.sql_render.Mapper">

    <select id="searchUsers" resultType="org.apache.ibatis.submitted.sql_render.User">
        SELECT
        id, name, email, status, age, created_at
        FROM users
        <where>
            <if test="statusList != null and statusList.size() > 0">
                AND status IN
                <foreach item="statusItem" collection="statusList" open="(" separator="," close=")">
                    #{statusItem}
                </foreach>
            </if>
            <if test="searchKeyword != null and searchKeyword != ''">
                <bind name="searchPattern" value="'%' + searchKeyword + '%'"/>
                AND (name LIKE #{searchPattern} OR email LIKE #{searchPattern})
            </if>
            <if test="registeredAfter != null">
                AND created_at &gt;= #{registeredAfter}
            </if>
            <if test="registeredBefore != null">
                AND created_at &lt;= #{registeredBefore}
            </if>
        </where>
        <choose>
            <when test="sortBy == 'nameAsc'">
                ORDER BY name ASC
            </when>
            <when test="sortBy == 'ageDesc'">
                ORDER BY age DESC
            </when>
            <when test="sortBy == 'newest'">
                ORDER BY created_at DESC
            </when>
            <otherwise>
                ORDER BY id ASC
            </otherwise>
        </choose>
    </select>

    <select id="searchUsersByStatus" resultType="org.apache.ibatis.submitted.sql_render.User">
        SELECT * FROM users WHERE status = #{status}
    </select>
</mapper>

=== vonlinee/mybatis-3/src/test/java/org/apache/ibatis/scripting/xmltags/Mapper.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!--

       Copyright 2009-2023 the original author or authors.

       Licensed under the Apache License, Version 2.0 (the "License");
       you may not use this file except in compliance with the License.
       You may obtain a copy of the License at

          https://www.apache.org/licenses/LICENSE-2.0

       Unless required by applicable law or agreed to in writing, software
       distributed under the License is distributed on an "AS IS" BASIS,
       WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
       See the License for the specific language governing permissions and
       limitations under the License.

-->
<!DOCTYPE mapper
    PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN"
    "https://mybatis.org/dtd/mybatis-3-mapper.dtd">

<mapper namespace="org.apache.ibatis.scripting.xmltags.Mapper">

  <sql id="byBlogId">
    <if test="blog_id != null">${prefix}_id = #{blog_id}</if>
  </sql>

  <select id="findPost" resultType="org.apache.ibatis.domain.blog.Post">
    SELECT *
    FROM POST P
    <if test="param.blog_title != null and param.blog_title != ''">${prefix}_id = #{blog_id}</if>
    <if test="param.author_name != null or param.author_name = ''">${prefix}_id = #{blog_id}</if>
    <where>
      <foreach collection="example.oredCriteria" item="criteria" separator="or">
        <if test="criteria.valid">
          <trim prefix="(" prefixOverrides="and" suffix=")">
            <foreach collection="criteria.criteria" item="criterion">
              <choose>
                <when test="criterion.noValue">
                  and ${criterion.condition}
                </when>
                <when test="criterion.singleValue">
                  and ${criterion.condition} #{criterion.value}
                </when>
                <when test="criterion.betweenValue">
                  and ${criterion.condition} #{criterion.value} and #{criterion.secondValue}
                </when>
                <when test="criterion.listValue">
                  and ${criterion.condition}
                  <foreach close=")" collection="criterion.value" item="listItem" open="("
                           separator=",">
                    #{listItem}
                  </foreach>
                </when>
              </choose>
            </foreach>
          </trim>
        </if>
      </foreach>
    </where>
  </select>
</mapper>

=== vonlinee/mybatis-3/src/test/resources/org/apache/ibatis/submitted/refid_resolution/ExternalMapper2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

       Copyright 2009-2026 the original author or authors.

       Licensed under the Apache License, Version 2.0 (the "License");
       you may not use this file except in compliance with the License.
       You may obtain a copy of the License at

          https://www.apache.org/licenses/LICENSE-2.0

       Unless required by applicable law or agreed to in writing, software
       distributed under the License is distributed on an "AS IS" BASIS,
       WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
       See the License for the specific language governing permissions and
       limitations under the License.

-->
<!DOCTYPE mapper
    PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN"
    "https://mybatis.org/dtd/mybatis-3-mapper.dtd">

<mapper namespace="org.apache.ibatis.submitted.refid_resolution.ExternalMapper2">
    <sql id="externalColumnList">
        field1, field2
    </sql>

    <sql id="externalPrivateColumnList" scope="private">
        field1, field2, field3
    </sql>

    <sql id="externalColumnList1">
        <include refid="externalPrivateColumnList"/>
    </sql>

    <insert id="insert" parameterType="map">
        <selectKey resultType="java.lang.Integer" keyProperty="id">
            CALL IDENTITY()
        </selectKey>
        insert into table1 (
        <include refid="externalPrivateColumnList" />
        ) values (#{field1},#{field2},#{field3})
    </insert>
</mapper>
